src/wasm/CMakeLists.txt
With this change it looks like this in Visual Studio:
=> Update CMakeLists to show all the header files in folders

.github/workflows/build.yml, README.md, src/wasm/CMakeLists.txt, src/wasm/deps/tinycpptest/LICENSE.md, src/wasm/deps/tinycpptest/TinyCppTest.hpp, src/wasm/test/core_test.cpp, src/wasm/test/main.cpp, src/wasm/test/util_test.cpp
Added a test skeleton:
- CMakeLists extended with test.
- One single test checking triangle area calculation.
- Added GitHub Action to run build and test.
- Added GitHub Actions badge to the readme file.
=> Add test skeleton using TinyCppTest

package-lock.json, package.json
=> update dependencies and remove deprecated module tsc

.vscode/settings.json, src/wasm/include/util.h, src/wasm/include/web-ifc-geometry.h, src/wasm/web-ifc-test.cpp
First attempt to solve and IFC issue
This is  basic contribution that needs further development
=> Add an L profile addressing issue no. 21

src/wasm/include/util.h, src/wasm/web-ifc-test.cpp
Este método lo propuso Tom, van casi igual, pero como hay menos cambios es más seguro. Básicamente en Util.h en la linea 607 he añadido una iteración para encontrar valores mejores de normales en la mayoria de los casos
=> Issue 102 version tom

src/wasm/include/web-ifc-geometry.h
There was a bug reading double values that prevented 3dtransformations to work
=> Problem reading doubles

src/wasm/include/web-ifc-geometry.h, src/wasm/include/web-ifc.h, src/wasm/web-ifc-test.cpp
Update:
- Now it sends a warning when some express lines are missing
- It is able to read IFCINDEXEDPOLYCURVE when it has a curve indices list
=> Issue 144 2

src/wasm/include/web-ifc-geometry.h, src/wasm/include/web-ifc.h, src/wasm/web-ifc-test.cpp
Now all axis are normalized when loaded for object placement. It completely solves Issue_131 BUT It must be extensively tested before be accepted as it modifies a core function.
=> Issue 131 2

src/wasm/include/util.h, src/wasm/include/web-ifc-geometry.h, src/wasm/web-ifc-test.cpp
#156 
APOGEA has added all basic elements to read advancedBreps, still missing many kinds of geometry that will be added later.
=> Issue 156 - First stage of AdvancedBreps

package-lock.json, package.json, tests/regression/.gitignore, tests/regression/public/index.html, tests/regression/public/viewer.html, tests/regression/src/index.js, tests/regression/src/loader.js, tests/regression/src/logger.js, tests/regression/src/viewer.js
Hey,
The idea here is to build up a regression testing framework that loads example models, and the result can be checked by some automation. This PR contains the basis for such a framework.
It gets the library from the  `dist` folder, so it always shows the latest state. I intentionally didn't use the official three.js loader since the goal here is to test the library itself, and not the loader. I've put together a very simple non-optimized loader to minimize the number of possible errors.
1. Run `npm run regression-test`.
2. Open http://localhost:8080/tests/regression/public in a web browser. You will see something like this:
3. Click on one of the links. Files are loaded from this repo: https://github.com/IFCjs/test-ifc-files. The result will look something like this:
I think it's …
=> Regression testing framework

src/wasm/include/web-ifc.h, src/wasm/web-ifc-test.cpp
Making header compatible with solibri
=> Solibricompatible

src/wasm/include/web-ifc-geometry.h, src/wasm/web-ifc-test.cpp
=> Improvement circular senseAgreement

src/wasm/include/util.h, src/wasm/include/web-ifc-geometry.h, src/wasm/web-ifc-test.cpp
Improvement in Inverse evaluation and bspline knots
=> Advanced breps

src/wasm/include/web-ifc-geometry.h
This pull solves the issue #21 and #121
=> Circle placement bug

tests/functional/WebIfcApi.spec.ts
Hi Antonio,
This test round-trips the written value to make sure it's present in memory after setting, and also is read back in after serialization.
=> Add test for #226.

examples/nodejs/index.js, src/wasm/include/web-ifc.h, src/wasm/web-ifc-api.cpp, src/wasm/web-ifc-test.cpp, src/web-ifc-api.ts
Some changes added to index.js, web-ifc-api.ts, web-ifc.h and web-ifc-api.cpp showing the potential use of IFC.JS to edit and add new properties and objects to IFC
=> Updated modify IFC example

src/wasm/include/web-ifc.h
Added a function to search for and replace lower case e with upper case E in doubles when writing stream to IFC file.
=> #214 added function to change e to E in doubles

src/wasm/include/web-ifc-geometry.h, src/wasm/include/web-ifc.h, src/wasm/web-ifc-test.cpp
In order to solve the issue #247:
Added derivedProfile, transformation2D and corrections to units transformation
=> Added derivedProfile

src/wasm/include/web-ifc-geometry.h, src/wasm/web-ifc-test.cpp
Problem generating halfspaces
Added regenerate xAxis in IFCAXIS2PLACEMENT3D
=> Issue #218

examples/nodejs/index.js, src/web-ifc-api.ts
I couldn't figure out the type signature so I parse the key to number.
Also there's an existing functional test for this, but NB a bunch of other tests currently aren't passing.
=> Fix for #285.

src/wasm/web-ifc-api.cpp
as per https://github.com/IFCjs/web-ifc/issues/104#issuecomment-1167262653
=> Add a callback progress

src/helpers/log.ts, src/web-ifc-api.ts
Add `Log` class in helpers/log.ts to separate out logging logic
Add & update comments in web-ifc-api.ts
=> Add Logger & comments

package-lock.json, package.json, src/wasm/CMakeLists.txt, src/web-ifc-api.ts, tests/functional/Properties.spec.ts
=> Revert "Improved Bundling"

src/helpers/properties.ts, src/web-ifc-api.ts
I noticed a x2 increase in our code speed by doing this small change. I tested it on the 0.40 code, but I think it should work in the current version
=> Increase in performance for properties

src/wasm/geometry/IfcGeometryLoader.cpp, src/wasm/geometry/IfcGeometryProcessor.cpp, src/wasm/geometry/IfcGeometryProcessor.h, src/wasm/geometry/operations/curve-utils.h
- Added support of UNION boolean operator 
- Added support of trapezium type of curve
=> Added missing geometry options

.vscode/settings.json, src/cpp/parsing/IfcLoader.cpp
double free may leads to crash under some compilers
=> avoid double free _nullLine

src/cpp/web-ifc/geometry/operations/geometryutils.h, src/cpp/web-ifc/schema/IfcSchemaManager.h
in VectorToAngle: add check for zero, to avoid inf values in mesh
=> in VectorToAngle: add check for zero, to avoid inf values in mesh

src/schema-generator/gen_functional_types.ts, src/schema-generator/gen_functional_types_helpers.ts
Resolve issues with primitive types (Real and Integer) and their values when reading and writing IFC files.
The following are the details of the issues:
- Due to double-to-string conversion(`webifc::parsing::IfcLoader::GetDoubleArgumentAsString()`), values are always returned as strings, when defined as primitive types.
```js
// EXPRESS specification
ENTITY IfcCartesianTransformationOperator
ABSTRACT SUPERTYPE OF (ONEOF
(IfcCartesianTransformationOperator2D
,IfcCartesianTransformationOperator3D))
SUBTYPE OF (IfcGeometricRepresentationItem);
Axis1 : OPTIONAL IfcDirection;
Axis2 : OPTIONAL IfcDirection;
LocalOrigin : IfcCartesianPoint;
Scale : OPTIONAL REAL; <--------------------- like this
DERIVE
Scl : REAL := NVL(Scale, 1.0);
Dim : IfcDimensionCount := LocalOrigin.Dim;
WHERE
WR1 : Scl > …
```
=> Fix handling primitive type value

src/cpp/web-ifc/geometry/IfcGeometryProcessor.cpp, src/cpp/web-ifc/geometry/IfcGeometryProcessor.h
Additionally, group geometry output settings in "struct IfcGeometrySettings" in IfcGeometryProcessor
=> Add option to export polylines as geometry

src/cpp/web-ifc/parsing/string_parsing.cpp
=> Fix Encoding
