ThatOpen/engine_web-ifc

- package-lock.json
- package.json
* update package.json dependencies
* update emscripten commands
* added `-s MAXIMUM_MEMORY=4GB`
*  Now my biggest IFC loads when I try it with `npm run dev` :-)
* updated deprecated arguments
More info about deprecated arguments
`
em++: warning: please replace -g4 with -gsource-map [-Wdeprecated]`
`em++: warning: EXTRA_EXPORTED_RUNTIME_METHODS is deprecated, please use EXPORTED_RUNTIME_METHODS instead [-Wdeprecated]`
> added Memory4gb, updated deprecated emscripten arguments, updated package.json dependencies

- package-lock.json
- package.json
According to the [node.js document](https://nodejs.org/api/packages.html#dual-commonjses-module-packages), the `"main"` field should be specifying the `cjs` entry point and the `"module"` field should be used for the `esm` entry point.
> Added module field in package.json to separate cjs and esm

- package.json
I've added a build step that generates the library as a non-module javascript file, so you can use it in the traditional way (no modules).
HTML:
```html
<script type="text/javascript" src="web-ifc-api-browser.js"></script>
```
JavaScript:
```js
let ifcAPI = new WebIFC.IfcAPI ();
// do the job
```
> Build non-module javascript api that can be used as a traditional javascript file

- src/web-ifc-api.ts
Added TODO with my guess that this is from over-recursion.
> Workaround for #178, skip writing primitives.

- src/web-ifc-api.ts
I tested this locally by changing that, building a new web-ifc@0.0.37, using npm pack to host the npm locally, building a new web-ifc-three-@0.0.122 that uses the new web-ifc, rebuilding the Crash Course example, and running it.  The written file now contains the IFCSTOREY with the new name.
5/5 tests in web-ifc pass.
7/12 tests in web-ifc-three pass, 5 fail.  However, never tried running tests here before.
> Fix typo from ToType to ToTape for #178.

- src/wasm/include/web-ifc.h
- src/wasm/web-ifc-api.cpp
- src/web-ifc-api.ts
- tests/functional/Properties.spec.ts
- tests/functional/WebIfcApi.spec.ts
This PR introduces configurable control of logging levels: DEBUG, INFO, WARN, ERROR, OFF.  This is used to optionalize the version logging, i.e. to disable for jsconsole and unit tests.
NOTE: I'm debugging an issue where setting the log level from the TS wrapper doesn't take effect.
> Log control

- src/wasm/include/web-ifc.h
- src/wasm/web-ifc-api.cpp
- src/web-ifc-api.ts
Added a validation check of the ExpressID to ensure it is in the IFC file checking for omitted intermediate ExpressIDs and returns an undefined value if the ExpressID doesn't exist to address #224
> #224 GetLine always returns the first LineID if its expressId not exist

- examples/viewer/web-ifc-viewer.ts
- src/helpers/properties.ts
- src/web-ifc-api.ts
Implemented a function to get a unique list of all IFC types within a given model returning an array of objects with typeID and typeName properties to address issue #213 
The function is asynchronous and returns a Promise so it needs to be awaited in an async function as demonstrated in the updated web-ifc-viewer.ts file.
The array can be iterated through to find the typeID and typeName as required by the developer
> #213 Added GetAllTypesOfModel function to WebAPI

- src/wasm/web-ifc-api.cpp
- src/web-ifc-api.ts
- tests/functional/WebIfcApi.spec.ts
Added the function GetNextExpressID to the API to retrieve the next highest express ID from the IFC model. This resolves the issue #230 . The function takes in 2 parameters: model ID and express ID for the model and expressID of interest
> #230 Get the next highest expressID: Added GetNextExpressID

- src/web-ifc-api.ts
Add support for writing new lines  in `WriteLine()`
If lineObject has expressID === undefined || < 0 , `IncrementMaxExpressID()` is called and assigned to expressID.   Checks for < 0, to be compliant with helper-classes, because instantiating those requires an `expressID: number`.    As `WriteLine()` is recursive, nested objects will have smaller expressIDs than the parent's.
> Add support for writing new lines

- .github/workflows/upload.yml
- src/wasm/CMakeLists.txt
Sometimes EMSCRIPTEN make silent changes. We should ensure our automated builds do not change version unless we want it
> Ensure a static version of EMSCRIPTEN 

- src/wasm/web-ifc-api.cpp
- src/web-ifc-api.ts
StreamMeshes is not well registered to be used in Javascript or Node
This commit solves the following,
- In the file `web-ifc-api.ts` it defines StreamMeshes to be used in Javascript or Node. 
- In the file `web-ifc-api.cpp` it defines and registers `StreamMeshesVal` to Javascript/Node and allow pass second parameter as Javscript/Node array
> =Fix registering StreamMeshes

- src/web-ifc-api.ts
Due to a change  between version 0.0.41 and 0.0.42 the GetModelSchema function returns undefined when a model was obtained with OpenModel. 
This change re-adds the required line to OpenModel.
> Add schema name when using OpenModel function

- src/web-ifc-api.ts
After updating from 0.40 to 0.42 this week, I checked if this issue got resolved with the last update. Sadly, seems like its producing a new error:
(issue) https://github.com/IFCjs/web-ifc/issues/381
(new error)
`
TypeError: Cannot use 'in' operator to search for 'GlobalId' in undefined
at IfcAPI2.CreateIfcGuidToExpressIdMapping (VM529 web-ifc-api-node.js:63494:24)
`
And I think the pull request that got accepted yesterday (https://github.com/IFCjs/web-ifc/pull/439), I think would return the old error again when 0.43 gets released
So here is my pull request with a suggestion that should work I think
> handle error if cant map expressid to globalid

- src/wasm/web-ifc-api.cpp
When a IFC line definition contains empty lists – e.g. () – the GetLine method throw an error. The problem is related to the GetArgs method defined in web-ifc-api.cpp where empty lists get interpreted as null.
> Prevent empty lists from being converted to null

- src/schema-generator/gen_functional_types_helpers.ts
Some authoring tools generate lines with empty values – $ – where the schema enforces a required value.
E.g. GetLine throw an error when loads the following line:
```
#105530 = IFCWINDOWSTYLE('12oXYiBIL5ZeOtcy16wePW', #8, 'Geschossdecke:XXX_PLATZHALTER_HOL_16', $, $, (#105531), $, '38382177', $, $, $, $);
```
This happens because the generated function is expecting the last two values to be a IfcBoolean crashing on `v[10].value` 
In the case of a IfcWindowStyle line, this is the related function:
```
1299126871: (id, v) => new IFC2X3.IfcWindowStyle(id, new IFC2X3.IfcGloballyUniqueId(v[0].value), new Handle(v[1].value), !v[2] ? null : new IFC2X3.IfcLabel(v[2].value), !v[3] ? null : new IFC2X3.IfcText(v[3].value), !v[4] ? null : new IFC2X3.IfcLabel(v[4].value), !v[5] ? null : v[5].map((p) …
```
> Prevent errors on GetLine when loading lines with mandatory attributes empty

- src/schema-generator/gen_functional_types_helpers.ts
With this change GetLine should be more permissive when reading an IFC line which doesn't strictly respect the standard definition. Specifically when a value is mandatory but the authoring tool generate a missing value – $ – GetLine throw an error.
> Prevent accessing value when v[i] is not defined.

- examples/viewer/web-ifc-three.ts
- package-lock.json
web-ifc-three: Fixed the renderization Front and Back face of mesh f)rom merged geometries. Before only Front face was renderered so it caused no render some parts like this example,
Now is fixed,
> viewer: Fixed the renderization Front and Back face

- src/schema-generator/gen_functional_types.ts
When parsing IFC numbers, boolean and logical, null values are not preserved. Numbers – e.g. IFCREAL or IFCINTEGER – are converted to NaN, booleans – IFCBOOLEAN – to false and logicals – IFCLOGICAL – to UNKNOWN. Since these conversions may be subjective, it would be more transparent to leave the API consumer to handle it.
> Preserve null values when parsing number, boolean and logical.

- src/cpp/parsing/IfcFileStream.cpp
When a text was being tokenized and the closing apostrophe falled at the end of the current content chunk, content part (equal to the size of the buffer -1) had been skipped.
> Fix large amount of content skipped when chunk ends with closing apostrophe

- package.json
Export wasm files in `package.json` so they can be imported in vite projects like this
```ts
import ifcWasmUrl from "web-ifc/web-ifc.wasm?url";
```
> Export wasm files

- src/cpp/wasm/web-ifc-wasm.cpp
- src/cpp/web-ifc/parsing/IfcLoader.cpp
- src/cpp/web-ifc/parsing/IfcLoader.h
Without ordering, the lines are in a random order, which makes it hard to track issues in exported files
> IfcLoader::SaveFile: option to order the STEP lines

- src/cpp/test/web-ifc-test.cpp
- src/cpp/wasm/web-ifc-wasm.cpp
- src/cpp/web-ifc/geometry/operations/bim-geometry/circularSweep.cpp
- src/cpp/web-ifc/geometry/operations/bim-geometry/circularSweep.h
- src/cpp/web-ifc/geometry/operations/bim-geometry/extrusion.cpp
- src/cpp/web-ifc/geometry/operations/bim-geometry/extrusion.h
- src/cpp/web-ifc/geometry/operations/bim-geometry/utils.h
- src/cpp/web-ifc/geometry/operations/geometryutils.h
- src/cpp/web-ifc/geometry/operations/mesh_utils.h
- src/ts/web-ifc-api.ts
This change isolates geometry functions from the rest of the code.
> Bim geometry

- src/cpp/CMakeLists.txt
This change makes 'HEAPU8','HEAPU32','HEAPF32' still available on ifcApi instance with latest version of emscripten.
This follows the comment I made in this issue: https://github.com/ThatOpen/engine_web-ifc/issues/1421
Thank you
Charles
> Update CMakeLists.txt for latest emscripten compatibility on node build
